name: Project 04 CD

on:
  workflow_run:
    workflows: ["Project 04 CI"]
    types:
      - completed

  workflow_dispatch:

jobs:

  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env File
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > project-04-zero-touch-cicd/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> project-04-zero-touch-cicd/.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> project-04-zero-touch-cicd/.env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> project-04-zero-touch-cicd/.env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> project-04-zero-touch-cicd/.env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> project-04-zero-touch-cicd/.env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> project-04-zero-touch-cicd/.env

      - name: Pull Latest Image
        run: |
          cd project-04-zero-touch-cicd
          docker compose pull web

      - name: Deploy Application
        run: |
          cd project-04-zero-touch-cicd
          docker compose up -d

      - name: Verify Deployment
        run: |
          curl -f http://localhost:5000
