name: Project 04 CI

on:
  push:

  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r project-04-zero-touch-cicd/app/requirements.txt
          pip install -r project-04-zero-touch-cicd/requirements-dev.txt

      - name: Run Ruff
        run: |
          ruff check .

      - name: Run Pytest
        run: |
          cd project-04-zero-touch-cicd 
          mkdir -p reports
          pytest --junitxml=reports/results.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report-${{ matrix.python-version }}
          path: project-04-zero-touch-cicd/reports/results.xml


  build:
    runs-on: ubuntu-latest
    needs: test

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image with Compose
        run: |
          cd project-04-zero-touch-cicd
          docker compose build web

      - name: Push Docker Image to Docker Hub
        run: |
          cd project-04-zero-touch-cicd
          docker compose push web
